constants.py added
pholleway/drcog-lulc pull request #5
Opened 2022-04-18 18:43 UTC by pholleway

Before you submit a pull request, please fill in the following:

**Related Issue(s):**
Initial src files set up. 

**Description:**
Included set up for contants.py and stac.py

**PR checklist:**

- [ ] Code is formatted (run `scripts/format`).
- [ ] Code lints properly (run `scripts/lint`).
- [ ] Tests pass (run `scripts/test`).
- [ ] Documentation has been updated to reflect changes, if applicable.
- [ ] Changes are added to the [CHANGELOG](../CHANGELOG.md).
- [ ] Examples are added to `examples/`

2022-04-21 20:40 UTC, pholleway commented
cc @gadomski

2022-04-25 21:13 UTC, gadomski commented
@pholleway _should_ be updated and hopefully CI passes. FYI you'll need to run the following to set up the new linting/formatting infrastructure in your virtual environment:

```shell
$ pip install -r requirements-dev.txt && pre-commit install
```

2022-04-26 11:37 UTC, gadomski requested changes
A more general note to go with my specific comments: can you add some text to the README describing the process by which the source ESRI-formatted file was converted to GeoTIFF?

2022-04-26 11:37 UTC, gadomski commented on docs/source/conf.py
> +copyright = "2022, Paola Holleway"
This copyright should be Microsoft.

2022-04-26 11:37 UTC, gadomski commented on src/stactools/drcog_lulc/constants.py
> +# and use a string separator. The same logic is applied to the mission.
This comment can be removed, this was for a different use-case where we had multiple missions.

2022-04-26 11:37 UTC, gadomski commented on src/stactools/drcog_lulc/constants.py
> +)
Can we put more information in the collection description? E.g. where the data were derived from, who owns the data, etc?

2022-04-26 11:37 UTC, gadomski commented on src/stactools/drcog_lulc/constants.py
> +        name="DRCOG",
I think we should use the full name here, e.g. "Denver Regional Council of Governments"

2022-04-26 11:37 UTC, gadomski commented on src/stactools/drcog_lulc/constants.py
> +    target="https://gis.drcog.org//rdc/supplemental/lulc_pilot_report.zip",  # noqa
```suggestion
    target="https://gis.drcog.org/rdc/supplemental/lulc_pilot_report.zip",
```

2022-04-26 11:37 UTC, gadomski commented on src/stactools/drcog_lulc/stac.py
> +        Item: STAC Item object representing the worldcover tile
```suggestion
        Item: STAC Item object representing the landcover GeoTIFF tile
```

2022-04-26 13:47 UTC, pholleway commented on docs/source/conf.py
> +copyright = "2022, Paola Holleway"
Updated to Microsoft

2022-04-26 13:49 UTC, pholleway commented on src/stactools/drcog_lulc/constants.py
> +# and use a string separator. The same logic is applied to the mission.
Comment removed

2022-04-26 13:50 UTC, pholleway commented on src/stactools/drcog_lulc/constants.py
> +        name="DRCOG",
Updated to full name.

2022-04-26 13:58 UTC, pholleway commented on src/stactools/drcog_lulc/constants.py
> +)
Added more information - owner/partnerships and data inputs.

2022-04-26 14:39 UTC, gadomski requested changes

2022-04-26 14:39 UTC, gadomski commented on src/stactools/drcog_lulc/constants.py
> +# and use a string separator. The same logic is applied to the mission.
```suggestion
```

2022-04-26 14:39 UTC, gadomski commented on src/stactools/drcog_lulc/constants.py
> +)
I don't see these changes.

2022-04-26 14:39 UTC, gadomski commented on src/stactools/drcog_lulc/constants.py
> +        name="DRCOG",
I don't see these changes.

2022-04-26 14:53 UTC, gadomski approved these changes

2022-04-26 16:04 UTC, merged